# AWS playbook
---

- name: EC2 instance creation
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    key_name: my_aws             # Key used for SSH
    region: ap-south-1           # Region of ec2 instance
    image: ami-05e00961530ae1b55 # AMI for Ubuntu-22.04 LTS
    id: "testing"
    instance_type: t2.micro       
    sec_group: "ec2User"         # Name of EC2 instance security group
    host_group: [ec2_instances]
    inventory_source: "{{ ansible_inventory_sources.0 }}"
    inventory_block: |
      {% for group in host_group %}
      [{{ group }}]
      {% for host in groups[group] %}
      {{ host }}
      {% endfor %}
      {% endfor %}


  tasks:
    - name: Provisioning EC2 instances
      block:
      - name: Create security group
        amazon.aws.ec2_security_group:
          name: "{{ sec_group }}"
          description: "Sec group for app"
          region: "{{ region }}"
          aws_access_key: "{{ ec2_access_key }}"  # From vault
          aws_secret_key: "{{ ec2_secret_key }}"  # From vault
          rules:                                
            - proto: tcp
              ports:
                - 22                            # allows ssh
                - 8080                          # http port for server
              cidr_ip: 0.0.0.0/0
              rule_desc: allow all incoming traffic on this port

      - name: Amazon EC2 | Create Key Pair      # Create key pair for ssh
        amazon.aws.ec2_key:
          name: "{{ key_name }}"
          region: "{{ region }}"
          aws_access_key: "{{ec2_access_key}}"  # From vault 
          aws_secret_key: "{{ec2_secret_key}}"  # From vault
          key_material: "{{ item }}"
        with_file: ~/.ssh/my_aws.pub

      - name: Start an instance with a public IP address
        amazon.aws.ec2_instance:
          name: "stemcell"
          key_name: "{{ key_name }}"
          instance_type: "{{ instance_type }}"
          security_group: "{{ sec_group }}"
          aws_access_key: "{{ ec2_access_key }}"
          aws_secret_key: "{{ ec2_secret_key }}"
          region: "{{ region }}"
          wait: yes
          wait_timeout: 300
          count: 1
          state: "running"
          network:
            assign_public_ip: true
          image_id: "{{ image }}"
          tags:
            Environment: Testing
        register: stemcell
        
      - name: Add newly created instances to host group
        become: yes
        ansible.builtin.add_host:
          hostname: "{{ item.public_ip_address }}"
          groups: "{{ host_group }}"
        loop: "{{ stemcell.instances }}"

      - name: Store host groups to inventory
        blockinfile:
          path: "{{ inventory_source }}"
          block: "{{ inventory_block }}"

      tags: ['never', 'create_ec2']
  